---
name: OPI PoC CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  # if workflow for PR or push is already running stop it, and start new one
  group: makefile-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: shellcheck
      run: |
        cd sw_firewall
        make -C build shellcheck

  run_poc:
    needs: shellcheck
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Setup IPDK
      run: |
        docker pull ghcr.io/ipdk-io/ipdk-ebpf-ubuntu2004-x86_64
        git clone https://github.com/ipdk-io/ipdk.git
        pushd ipdk/build
        ./ipdk install ebpf-ubuntu2004
        popd || exit

    - name: Install ipdk-plugin
      run: |
        mkdir -p ~/go/src
        pushd ~/go/src || exit
        git clone https://github.com/mestery/ipdk-plugin.git
        cd ipdk-plugin
        go get
        go build
        popd || exit

    - name: Run PoC
      run: |
        ./sw_firewall/scripts/poc.sh start
